language: node_js
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
before_script:
  - psql -c 'create database planning;' -U postgres
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
